# Generated by Django 3.2.18 on 2023-06-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230629_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
