# Generated by Django 3.2.18 on 2023-07-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voetbalspeler',
            old_name='created_date',
            new_name='datum_aanpassing',
        ),
        migrations.RenameField(
            model_name='voetbalspeler',
            old_name='published_date',
            new_name='datum_invoer',
        ),
        migrations.RenameField(
            model_name='voetbalspeler',
            old_name='author',
            new_name='naam_auteur',
        ),
        migrations.RenameField(
            model_name='voetbalspeler',
            old_name='name',
            new_name='naam_speler',
        ),
    ]
