# Generated by Django 3.2.18 on 2023-07-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_voetbalspeler_aangepast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voetbalspeler',
            name='aangepast',
        ),
    ]
