# Generated by Django 3.2.18 on 2023-07-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_voetbalspeler_aangepast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voetbalspeler',
            name='datum_aanpassing',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
