# Generated by Django 3.2.18 on 2023-07-06 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_voetbalspeler_datum_aanpassing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='voetbalspeler',
            name='datum_aanpassing',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
