# Generated by Django 3.2.18 on 2023-07-06 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20230706_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.RemoveField(
            model_name='voetbalspeler',
            name='datum_invoer',
        ),
        migrations.AddField(
            model_name='voetbalspeler',
            name='datum_aanmaak',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
