# Generated by Django 3.2.18 on 2023-07-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20230706_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voetbalspeler',
            name='datum_aanpassing',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
