# Generated by Django 3.2.18 on 2023-07-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_voetbalspeler_datum_aanpassing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voetbalspeler',
            old_name='datum_aanmaak',
            new_name='datum_invoer',
        ),
    ]
