# Generated by Django 3.2.18 on 2023-07-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_datum_aanmaak_voetbalspeler_datum_invoer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voetbalspeler',
            name='datum_invoer',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
