# Generated by Django 3.2.18 on 2023-07-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_voetbalspeler_datum_invoer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voetbalspeler',
        ),
    ]
